a=float(input("Enter your GPA: "))
if a<=10 and a>=9 : print("Your grade is A++")
elif a<9 and a>=8 : print("Your grade is A+")
elif a<8 and a>=7 : print("Your grade is A")
elif a<7 and a>=6 : print("Your grade is B++")
elif a<6 and a>=5 : print("Your grade is B+")
elif a<5 and a>=4 : print("Your grade is B")
elif a<4 and a>=3 : print("Your grade is C")
elif a<3 and a>=2 : print("Your grade is Q")
elif a<2  : print("D")
else : print("The number must be less than 11.Please enter valid number.")
